alias rp="grep -P"
alias v="nvim"
alias fx="waterfox"
alias pshdt="bash ~/.config/scripts/pushconfig.sh"
alias plldt="bash ~/.config/scripts/getconfig.sh"
alias nrd='npm run dev'
alias gcl="git clone"
alias gc="git commit"
alias ls="eza --icons=auto --color=auto"
alias l="eza --icons=auto -l --git --time-style=long-iso"
alias la="eza --icons=auto  --git -lA"
alias ltl="eza --icons=auto  --git -TlL"
alias ltt="eza --icons=auto  -T --git"
alias lt="eza --icons=auto  -Tl --git"
alias lta="eza --icons=auto  -Tla --git"
alias lsp="eza --icons=auto  -l --git --no-filesize --no-time --no-user"
alias sss="systemctl"
alias vir="virsh -c qemu:///system"
# alias lss="eza -l --git --no-filesize --icons=always --no-time --no-user --no-permissions"
# alias lsa="eza -lba --git --icons=always --total-size"
alias se="set -o emacs"
alias sv="set -o vi"
